#!/bin/bash
# Sync feature_list.json → Hearth todos after every commit.
# Auto-generated by `make hook-install` — re-generate by running: make hook-install
# Silently skips if the API is unreachable or credentials are missing.
REPO="{{APP_DIR}}"
ENV_FILE="$REPO/infra/local.env"
if [ -f "$ENV_FILE" ]; then
  set -a && . "$ENV_FILE" && set +a
fi
"$REPO/api/.venv/bin/python3.12" "$REPO/infra/scripts/sync-todos.py" 2>&1 \
  | sed 's/^/  [sync-todos] /' || true
