#!/bin/bash
# Auto-generated by `service.sh install` — do not edit directly.
# Re-generate by running:  ./infra/scripts/service.sh install

# launchd starts processes with a minimal PATH that won't include Node.
# Prepend the Node bin directory detected at install time so `next` can
# resolve `env node` internally.
export PATH="{{NODE_DIR}}:$PATH"

set -a
[ -f "{{APP_DIR}}/infra/local.env" ] && . "{{APP_DIR}}/infra/local.env"
set +a

exec "{{APP_DIR}}/web/node_modules/.bin/next" dev \
    --hostname 0.0.0.0 \
    --port 1337
