#!/bin/bash
# Auto-generated by `make bot-install` — do not edit directly.
# Re-generate by running: make bot-install

# Extend PATH so the claude binary (installed via npm or elsewhere) is findable.
export PATH="/opt/homebrew/bin:/usr/local/bin:$HOME/.npm/bin:$HOME/.local/bin:/usr/bin:/bin:$PATH"

set -a
[ -f "{{APP_DIR}}/infra/local.env" ] && . "{{APP_DIR}}/infra/local.env"
set +a

exec "{{APP_DIR}}/api/.venv/bin/python3.12" "{{APP_DIR}}/infra/scripts/hearth-bot.py"
