#!/bin/bash
# Auto-generated by `service.sh install` — do not edit directly.
# Re-generate by running:  ./infra/scripts/service.sh install

set -a
[ -f "{{APP_DIR}}/infra/local.env" ] && . "{{APP_DIR}}/infra/local.env"
set +a

# Wait for Postgres to be ready before starting the API.
# pg_isready exits 0 when the server is accepting connections.
PG_ISREADY="{{PG_BIN_DIR}}/pg_isready"
MAX_WAIT=60
waited=0
until "$PG_ISREADY" -h 127.0.0.1 -p 5432 -U {{PG_SUPERUSER}} -q; do
    if [ "$waited" -ge "$MAX_WAIT" ]; then
        echo "Timed out waiting for Postgres after ${MAX_WAIT}s" >&2
        exit 1
    fi
    sleep 1
    waited=$((waited + 1))
done

# Run any pending Alembic migrations before starting the server.
# No-op on SQLite; applies pending migrations on Postgres.
cd "{{APP_DIR}}/api" && .venv/bin/alembic upgrade head

exec "{{APP_DIR}}/api/.venv/bin/uvicorn" life_dashboard.main:app \
    --host 0.0.0.0 \
    --port 1338 \
    --reload \
    --reload-dir "{{APP_DIR}}/api/src"
